flysystem:
  storages:
    default.storage:
      adapter: "local"
      options:
        directory: "%kernel.project_dir%/public/images"
    user.storage:
      adapter: "local"
      options:
        directory: "%kernel.project_dir%/public/images/users"
    gas_stations.storage:
      adapter: "local"
      options:
        directory: "%kernel.project_dir%/public/images/gas_stations"
    gas_stations_brand.storage:
      adapter: "local"
      options:
        directory: "%kernel.project_dir%/public/images/gas_stations_brand"
    gas_types.storage:
      adapter: "local"
      options:
        directory: "%kernel.project_dir%/public/images/gas_types"
