version: '3.5'

services:
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: .
      dockerfile: ./.deployment/docker/containers/php/Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    networks:
      service:
        aliases:
          - pod
    environment:
      - ENV=/home/www-data/.ashrc
    volumes:
      - ./:/srv/app/:rw
      - ./.deployment/docker/containers/php/www.conf:/etc/php8.1.3/php-fpm.conf
      - ./.deployment/docker/containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./.deployment/docker/aliases/.ashrc:/home/www-data/.ashrc
    command: --define opcache.validate_timestamps=On

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    depends_on:
      - php
    image: nginx:1.20-alpine
    ports:
      - 8085:8080
    environment:
      - HTTPS_METHOD=noredirect
    networks:
      - service
    volumes:
      - ./public:/srv/app/public:ro
      - ./.deployment/docker/containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  database:
    container_name: ${PROJECT_NAME}_database
    image: mariadb:10.4.19
    env_file:
      - .env
    networks:
      - service
    ports:
      - 33182:3306
    volumes:
      - database_docker:/var/lib/mysql

  qa:
    container_name: ${PROJECT_NAME}_qa
    image: jakzal/phpqa:latest

volumes:
  database_docker: {}

networks:
  service:
    name: service
    external: true
